objects/Carousel__c/Carousel__c.object-meta.xml
<CustomObject>
    <description>Use this as control object to support experience community navigation tiles via custom component named, TeaserTileComponent.</description>
    <label>Community Carousel</label>
    <nameField>
        <label>Carousel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Carousels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Carousel_Tile__c/Carousel_Tile__c.object-meta.xml
<CustomObject>
    <description>This is back end control object for experience community interface navigation tiles.</description>
    <label>Community Carousel Tile</label>
    <nameField>
        <label>Carousel Tiles Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Carousel Tiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Carousel_Tile__c/fields/Carousel__c.field-meta.xml
<CustomField>
    <fullName>Carousel__c</fullName>
    <label>Carousel</label>
    <referenceTo>Carousel__c</referenceTo>
    <relationshipName>Carousel_Tiles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Carousel_Tile__c/fields/Tile_Content_Height__c.field-meta.xml
<CustomField>
    <fullName>Tile_Content_Height__c</fullName>
    <label>Tile Content Height</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Carousel_Tile__c/fields/Tile_Font_Color__c.field-meta.xml
<CustomField>
    <fullName>Tile_Font_Color__c</fullName>
    <label>Tile Font Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Carousel_Tile__c/fields/Tile_Image__c.field-meta.xml
<CustomField>
    <fullName>Tile_Image__c</fullName>
    <label>Tile Image</label>
    <type>Url</type>
</CustomField>

objects/Carousel_Tile__c/fields/Tile_Image_Height__c.field-meta.xml
<CustomField>
    <fullName>Tile_Image_Height__c</fullName>
    <label>Tile Image Height</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Carousel_Tile__c/fields/Tile_Order__c.field-meta.xml
<CustomField>
    <fullName>Tile_Order__c</fullName>
    <label>Tile Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/Carousel_Tile__c/fields/Tile_Width__c.field-meta.xml
<CustomField>
    <fullName>Tile_Width__c</fullName>
    <label>Tile Width</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

classes/TeaserTileComponentController.cls
/**
 * @description       : 
 * @author            : SFDX
 * @group             : 
 * @last modified on  : 10-12-2021
 * @last modified by  : SFDX
**/
public without sharing class TeaserTileComponentController {
    @AuraEnabled
    public static List<Carousel_Tile__c> getCarouselTile( String carouselName ){
        try {
            return new List<Carousel_Tile__c>([ SELECT Id, Name, Carousel__r.Name, Tile_Font_Color__c, Tile_Image__c, Tile_Order__c,Description__c,
                                                         Url__c, Tile_Image_Height__c, Tile_Content_Height__c, Tile_Width__c  
                                                FROM Carousel_Tile__c
                                                WHERE Carousel__r.Name =: carouselName
                                                ORDER BY Tile_Order__c ASC ]);
            
        } catch (Exception e) {throw new AuraHandledException(e.getMessage());
        }
    }
    
}